[package]
name = "sort"
version = "1.0.0"
description = "Radix sort"
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
core = "2.0.0"

[dev-dependencies]
bench = "1.0.0"
zhus = "https://github.com/ZhenyaUsenko/motoko-sort#main@73128b8bc6fa35e57ee6a45ba4cd18be33df3834"

[requirements]
moc = "0.16.3"

[toolchain]
moc = "1.0.0"
