[package]
name = "radix-sort"
version = "1.0.0"
description = "Radix sort"
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
core = "1.0.0"

[dev-dependencies]
bench = "1.0.0"
zhus = "https://github.com/ZhenyaUsenko/motoko-sort#main"

[requirements]
moc = "0.16.3"

[toolchain]
moc = "0.16.3"
